accounts/urls.py
from django.urls import path, include
from.import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from.import views

#Give urls a namespace to avoid namespace conflict
app_name = 'articles'
#Setup urls for the articles app
urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug>', views.article_detail, name='detail'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from.import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', views.home)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, default=None)

#python manage.py makemagrations
#python manage.py migrate
#python manage.py runserver
#python manage.py startapp appname
#python manage.py shell
#python manage.py createsuperuser

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:20] + '...'

articles/forms.py
from django import forms
from.import models

class CreateArticle(forms.ModelForm):
    class Meta:
         model = models.Article
         fields = ['title','slug','body','thumbnail']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
#Redirect to the previous page initially accessed
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')    
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from.import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
       form = forms.CreateArticle(request.POST, request.FILES)
       if form.is_valid():
           save_article = form.save(commit=False)
           save_article.author = request.user
           save_article.save()
           return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

djangoblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form method="post" action="{% url 'accounts:login' %}" class="site-form">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form method="post" action="{% url 'accounts:signup'%}" class="site-form">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Article create</h2>
    <form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit">Create</button>
    </form>
    <script src="/static/js/slugify.js" type="text/javascript"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>{{article.title}}</h1>
    <div class="articles">
        <img src="{{article.thumbnail.url}}" alt="">
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="ariticle">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
                <p>{{article.author}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Articles</title>
</head>
<body>
    <div class="container">
        <h1><a href="{% url 'articles:list' %}">Articles</a></h1>
        {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            <a href="{% url 'articles:create' %}">Create Articles</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:signup' %}">Signup</a>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/home.html
{% extends 'base_layout.html' %}

{% block content %}
    <h3>Click link to access articles</h3>
{% endblock %}